services:

  frontend:
    image: vinaysingh0912/myapp-frontend:${IMAGE_TAG:-latest}
    restart: unless-stopped
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    image: vinaysingh0912/myapp-backend:${IMAGE_TAG:-latest}
    restart: unless-stopped
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env