// Import mongoose so our test can connect to MongoDB
// and interact with the database (save, find, delete documents)
import mongoose from 'mongoose';

// Import MongoMemoryServer so we can create a temporary
// MongoDB database in RAM instead of using our real database
import { MongoMemoryServer } from 'mongodb-memory-server';

// Import the User model that we manually wrote in Sprint 1
// This is the actual code we are testing
import User from '../../src/models/User';

// 'describe' groups related tests together under a label
// All 11 User Model tests will live inside this block
describe('User Model', () => {

    // Declare the variable that will hold our in-memory MongoDB server
    // We declare it here (outside beforeAll/afterAll) so that
    // ALL functions inside this describe block can access it
    let mongoServer: MongoMemoryServer;

    // beforeAll runs ONCE before any test in this describe block
    // 'async' means this function contains operations that take time
    // We must wait for the database to be ready before running tests
    beforeAll(async () => {

        // Step 1: Create a brand new MongoDB server in RAM
        // MongoMemoryServer.create() downloads/starts a real MongoDB process
        // 'await' means "wait here until the server is fully started"
        mongoServer = await MongoMemoryServer.create();

        // Step 2: Get the connection address (URI) of the in-memory server
        // This gives us something like: 'mongodb://127.0.0.1:54321/'
        // This is NOT our real database URI from .env
        const uri = mongoServer.getUri();

        // Step 3: Connect Mongoose to the temporary in-memory database
        // 'await' means "wait here until the connection is fully established"
        // After this line, Mongoose can save/read documents from the temp database
        await mongoose.connect(uri);
    });

    // afterAll runs ONCE after all tests finish
    // We clean up the database and stop the in-memory server
    afterAll(async () => {
        await mongoose.connection.dropDatabase();
        await mongoose.connection.close();
        await mongoServer.stop();
    });

   // afterEach runs after EACH individual test (not once — every time)
    // Why? Test 7 saves a user with email "duplicate@example.com"
    // If we don't delete it, Test 8 might fail because that data is still there
    // Each test must start with an EMPTY database — no leftover data
    afterEach(async () => {
        // mongoose.connection.collections gives us an object like:
        // { users: Collection, ... }
        // It contains every collection that exists in our temp database
        const collections = mongoose.connection.collections;
        // 'for...in' loops through each key (collection name) in the object
        // For our tests, the main one will be 'users'
        for (const key in collections) {
            // deleteMany({}) means "delete ALL documents where filter = {}"
            // An empty filter {} matches everything — so it deletes everything
            // await because deleting from a database takes time
            await collections[key].deleteMany({});
        }
    });

       // TEST 1: Can we save a user with all required fields?
    // This is the "happy path" — everything is correct, nothing missing
    it('should create and save a user successfully with required fields', async () => {

        // Step 1: Create a new User document in memory (NOT saved to DB yet)
        // 'new User({...})' creates a JavaScript object based on our schema
        // At this point, MongoDB has no idea this user exists
        const validUser = new User({
            name: 'Test User',
            email: 'test@example.com',
            passwordHash: 'hashed_password_123'
        });

        // Step 2: Actually save it to the database
        // .save() sends the document to MongoDB and waits for confirmation
        // MongoDB assigns an _id and returns the saved document
        const savedUser = await validUser.save();

        // Step 3: Check that everything was saved correctly
        // _id is auto-generated by MongoDB — if it exists, the save worked
        expect(savedUser._id).toBeDefined();
        // These 3 should exactly match what we passed in
        expect(savedUser.name).toBe('Test User');
        expect(savedUser.email).toBe('test@example.com');
        expect(savedUser.passwordHash).toBe('hashed_password_123');
    });

       // TEST 2: Does isEmailVerified default to false?
    // In our schema, we set: default: false
    // So if we never provide isEmailVerified, Mongoose should set it to false automatically
    it('should default isEmailVerified to false if not provided', async () => {

        // We deliberately do NOT include isEmailVerified in the object
        const user = new User({
            name: 'Default Test',
            email: 'default@example.com',
            passwordHash: 'hashed_password_123'
        });

        const savedUser = await user.save();

        // We never set isEmailVerified, so Mongoose uses the default: false
        // .toBe(false) checks for an exact match — it must be boolean false
        expect(savedUser.isEmailVerified).toBe(false);
    });

    // TEST 3: Does Mongoose reject a user without a name?
    // In our schema, name has: required: true
    // So saving without a name should throw a ValidationError
    it('should fail validation if name is missing', async () => {

        // We create a user WITHOUT the 'name' field
        const userWithoutName = new User({
            email: 'noname@example.com',
            passwordHash: 'hashed_password_123'
        });

        // We use try/catch instead of expect().toThrow() because .save() is async
        // try = "attempt this code"
        // catch = "if it throws an error, catch it here instead of crashing"
        let error: any;
        try {
            await userWithoutName.save();
        } catch (err) {
            // If .save() fails, the error lands here
            error = err;
        }

        // The error should exist (meaning .save() did fail)
        expect(error).toBeDefined();
        // Mongoose names this type of error 'ValidationError'
        expect(error.name).toBe('ValidationError');
        // The error.errors object has a key for each field that failed
        // We check that 'name' is one of the failing fields
        expect(error.errors.name).toBeDefined();
    });

    // TEST 4: Does Mongoose reject a user without an email?
    // Same pattern as Test 3, but this time we leave out 'email'
    it('should fail validation if email is missing', async () => {

        // We have name and passwordHash, but NO email
        const userWithoutEmail = new User({
            name: 'No Email User',
            passwordHash: 'hashed_password_123'
        });

        // Same try/catch pattern — attempt to save, catch the error
        let error: any;
        try {
            await userWithoutEmail.save();
        } catch (err) {
            error = err;
        }

        expect(error).toBeDefined();
        expect(error.name).toBe('ValidationError');
        // This time we check error.errors.email (not .name like Test 3)
        expect(error.errors.email).toBeDefined();
    });

    // TEST 5: Does Mongoose reject a user without a passwordHash?
    // Last of the 3 required-field tests — same pattern as Tests 3 and 4
    it('should fail validation if passwordHash is missing', async () => {

        // We have name and email, but NO passwordHash
        const userWithoutPassword = new User({
            name: 'No Password User',
            email: 'nopassword@example.com'
        });

        let error: any;
        try {
            await userWithoutPassword.save();
        } catch (err) {
            error = err;
        }

        expect(error).toBeDefined();
        expect(error.name).toBe('ValidationError');
        // Check that 'passwordHash' is the field that failed
        expect(error.errors.passwordHash).toBeDefined();
    });

        
    // TEST 6: Does the schema convert email to lowercase?
    // In our schema, email has: lowercase: true
    // So "TEST@EXAMPLE.COM" should become "test@example.com" after saving
    it('should convert email to lowercase before saving', async () => {

        // We deliberately pass an UPPERCASE email
        const user = new User({
            name: 'Uppercase Email',
            email: 'TEST@EXAMPLE.COM',
            passwordHash: 'hashed_password_123'
        });

        const savedUser = await user.save();

        // Mongoose should have automatically lowercased it before saving
        // This proves the 'lowercase: true' option in the schema works
        expect(savedUser.email).toBe('test@example.com');
    });

        // TEST 7: Can two users have the same email?
    // In our schema, email has: unique: true
    // So saving a second user with the same email should fail
    it('should enforce unique email constraint', async () => {

        // Save the first user — this should work fine
        const firstUser = new User({
            name: 'First User',
            email: 'duplicate@example.com',
            passwordHash: 'hashed_password_123'
        });
        await firstUser.save();

        // Now try to save a SECOND user with the exact same email
        const secondUser = new User({
            name: 'Second User',
            email: 'duplicate@example.com',
            passwordHash: 'hashed_password_456'
        });

        let error: any;
        try {
            await secondUser.save();
        } catch (err) {
            error = err;
        }

        // This is NOT a Mongoose ValidationError
        // It's a MongoDB duplicate key error — error code 11000
        // MongoDB itself rejects the duplicate, not Mongoose
        expect(error).toBeDefined();
        expect(error.code).toBe(11000);
    });


        // TEST 8: Can we save a user WITHOUT profileData?
    // profileData has no 'required: true' in our schema
    // So it should be completely optional — the user saves fine without it
    it('should save successfully without profileData', async () => {

        const user = new User({
            name: 'No Profile',
            email: 'noprofile@example.com',
            passwordHash: 'hashed_password_123'
            // Notice: no profileData here
        });

        const savedUser = await user.save();

        // The save should succeed (no error thrown)
        // And profileData should be undefined — it was never set
        // .toBeUndefined() checks that the value is exactly 'undefined'
        expect(savedUser.profileData).toBeUndefined();
    });

        // TEST 9: Can we save a user WITH profileData?
    // profileData has type: Object in our schema
    // So it should accept any JavaScript object with any keys
    it('should save profileData when provided', async () => {

        const user = new User({
            name: 'With Profile',
            email: 'profile@example.com',
            passwordHash: 'hashed_password_123',
            // profileData can hold anything — phone, avatar, bio, etc.
            profileData: { phone: '1234567890', avatar: 'avatar.png' }
        });

        const savedUser = await user.save();

        // profileData should exist this time
        expect(savedUser.profileData).toBeDefined();
        // 'as any' tells TypeScript: "trust me, I know this has a .phone property"
        // Without it, TypeScript would complain because Record<string, any> is too generic
        expect((savedUser.profileData as any).phone).toBe('1234567890');
        expect((savedUser.profileData as any).avatar).toBe('avatar.png');
    });

        // TEST 10: Does Mongoose automatically add createdAt and updatedAt?
    // In our schema, we passed { timestamps: true } as the second argument
    // This tells Mongoose to auto-create these two Date fields on every save
    it('should automatically add createdAt and updatedAt timestamps', async () => {

        const user = new User({
            name: 'Timestamp User',
            email: 'timestamp@example.com',
            passwordHash: 'hashed_password_123'
            // Notice: we never set createdAt or updatedAt ourselves
        });

        const savedUser = await user.save();

        // Both timestamps should exist even though we never set them
        expect(savedUser.createdAt).toBeDefined();
        expect(savedUser.updatedAt).toBeDefined();
        // They should be Date objects (not strings, not numbers)
        // .toBeInstanceOf(Date) checks: "is this value created by the Date class?"
        expect(savedUser.createdAt).toBeInstanceOf(Date);
        expect(savedUser.updatedAt).toBeInstanceOf(Date);
    });

        // TEST 11: Does updatedAt change when we modify and re-save a document?
    // createdAt should stay the same forever, but updatedAt should refresh
    it('should update the updatedAt timestamp when document is modified', async () => {

        // Step 1: Create and save a user
        const user = new User({
            name: 'Update Test',
            email: 'update@example.com',
            passwordHash: 'hashed_password_123'
        });
        const savedUser = await user.save();

        // Step 2: Store the original updatedAt so we can compare later
        const originalUpdatedAt = savedUser.updatedAt;

        // Step 3: Wait 50 milliseconds
        // Why? Computers are FAST — save + re-save could happen in the same millisecond
        // If both happen at the same millisecond, the timestamps would be identical
        // and our test would pass for the wrong reason
        // 50ms delay guarantees a visible time difference
        await new Promise(resolve => setTimeout(resolve, 50));

        // Step 4: Change something and save again
        savedUser.name = 'Updated Name';
        const updatedUser = await savedUser.save();

        // Step 5: Verify updatedAt is now a later time
        // .getTime() converts a Date to milliseconds (e.g. 1723456789000)
        // So we're comparing two numbers: new time >= old time
        expect(updatedUser.updatedAt.getTime()).toBeGreaterThanOrEqual(originalUpdatedAt.getTime());
        // Also verify the name actually changed
        expect(updatedUser.name).toBe('Updated Name');
    });
}); // This closes the describe('User Model') block from line 15
